import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async ({ page }) => {
  await page.goto('/test-components.html')
})

test('nullable actuals, zero and completion are distinct from the prescription', async ({ page }) => {
  const coach = page.getByRole('region', { name: 'Coach set' })
  const client = page.getByRole('region', { name: 'Client set' })
  await expect(client.getByLabel('Actual load (kg)')).toHaveValue('')
  await expect(client.getByLabel('Set completed')).not.toBeChecked()
  await client.getByLabel('Actual load (kg)').fill('0')
  await client.getByLabel('Actual reps', { exact: true }).fill('0')
  await expect(client.getByText('Actual: 0 kg · 0 reps · RIR not recorded')).toBeVisible()
  await expect(client.getByLabel('Set completed')).not.toBeChecked()
  await client.getByLabel('Set completed').check()
  await client.getByLabel('Actual load (kg)').fill('')
  await expect(client.getByText('Actual: Load not recorded · 0 reps · RIR not recorded')).toBeVisible()
  await expect(coach.getByLabel('Load (kg)', { exact: true })).toHaveValue('60')
})

test('coach superset uses one after-round rest and clients retain separate exercise results', async ({ page }) => {
  const section = page.locator('#superset')
  await section.locator('label').filter({ hasText: /^Coach$/ }).click()
  await expect(section.getByLabel('Rest after complete round (s)')).toHaveCount(1)
  await expect(section.getByLabel('Rest after set (s)')).toHaveCount(0)
  await section.getByLabel('Rest after complete round (s)').fill('120')
  await section.locator('label').filter({ hasText: /^Client$/ }).click()
  const round1 = section.getByRole('group', { name: 'Round 1', exact: true })
  const round2 = section.getByRole('group', { name: 'Round 2', exact: true })
  const first = round1.getByRole('article', { name: 'A1 Barbell bench press' })
  const second = round1.getByRole('article', { name: 'A2 Barbell bent over row' })
  await first.getByLabel('Actual load (kg)').fill('52.5')
  await first.getByLabel('Actual reps', { exact: true }).fill('7')
  await first.getByLabel('Set completed').check()
  await expect(second.getByLabel('Actual load (kg)')).toHaveValue('')
  await expect(round2.getByLabel('Actual load (kg)').first()).toHaveValue('')
  await expect(round1.getByText('Rest 120 s after the pair.')).toBeVisible()
  const order = await round1.getByRole('article').evaluateAll(items => items.map(item => item.getAttribute('aria-label')))
  expect(order).toEqual(['A1 Barbell bench press', 'A2 Barbell bent over row'])
  await section.locator('label').filter({ hasText: /^Review$/ }).click()
  await expect(section.getByText('Actual: 52.5 kg · 7 reps · RIR not recorded')).toBeVisible()
  await expect(section.getByRole('spinbutton')).toHaveCount(0)
  await section.locator('label').filter({ hasText: /^Client$/ }).click()
  await expect(first.getByLabel('Actual load (kg)')).toHaveValue('52.5')
  await section.getByRole('button', { name: 'Reset block' }).click()
  await expect(first.getByLabel('Actual load (kg)')).toHaveValue('')
  await expect(first.getByLabel('Set completed')).not.toBeChecked()
})

test('exercise guidance failure does not discard set entries', async ({ page }) => {
  await page.route('**/videos/*.gif', route => route.abort())
  const exercise = page.locator('#exercise')
  await exercise.getByLabel('Actual reps', { exact: true }).first().fill('8')
  await exercise.getByRole('button', { name: 'Exercise guidance' }).click()
  await exercise.getByRole('button', { name: 'Play demonstration' }).click()
  await expect(exercise.getByText('Demonstration unavailable')).toBeVisible()
  await expect(exercise.getByText('© Gym visual — https://gymvisual.com/')).toBeVisible()
  await expect(exercise.getByLabel('Actual reps', { exact: true }).first()).toHaveValue('8')
  await exercise.getByRole('button', { name: 'Exercise guidance' }).click()
  await expect(exercise.getByLabel('Actual reps', { exact: true }).first()).toHaveValue('8')
})

test('catalogue search supports no-match and missing-media states', async ({ page }) => {
  const section = page.locator('#catalogue')
  await section.getByLabel('Library exercise', { exact: true }).click()
  await section.getByLabel('Library exercise', { exact: true }).fill('not-a-movement')
  await expect(page.getByText('No matching exercises')).toBeVisible()
  await page.keyboard.press('Escape')
  await section.getByLabel('Library exercise', { exact: true }).fill('Barbell bent')
  await page.getByRole('option', { name: 'Barbell bent over row (barbell)' }).click()
  await expect(section.getByRole('heading', { name: 'Barbell bent over row' })).toBeVisible()
  await section.getByRole('switch', { name: 'Demonstration unavailable example' }).check()
  await expect(section.getByText('No demonstration available for this exercise.')).toBeVisible()
})

test('programme composes weeks, sessions and blocks and publishes deliberately', async ({ page }) => {
  const section = page.locator('#programme')
  await expect(section.getByText('Only you can see this draft.')).toBeVisible()
  await section.getByRole('button', { name: 'Week 1 · 1 session' }).click()
  await expect(section.getByRole('heading', { name: 'Superset A' })).toBeVisible()
  await expect(section.getByLabel('Rest after complete round (s)')).toHaveValue('90')
  await section.getByRole('button', { name: 'Week 2 · 0 sessions' }).click()
  await expect(section.getByText('No sessions in this week yet.')).toBeVisible()
  await section.getByRole('button', { name: 'Publish programme' }).click()
  await expect(section.getByText('published', { exact: true })).toBeVisible()
  await expect(section.getByRole('button', { name: 'Publish programme' })).toHaveCount(0)
})

test('feedback has no inferred wellbeing defaults and clears inapplicable pain detail', async ({ page }) => {
  const section = page.locator('#workouts')
  await section.getByRole('button', { name: 'Save feedback' }).click()
  await expect(section.locator('pre')).toContainText('"pain_reported": null')
  await expect(section.locator('pre')).toContainText('"sleep_hours": null')
  await expect(section.locator('pre')).toContainText('"energy": null')
  await section.getByRole('radio', { name: 'Yes', exact: true }).check()
  await section.getByLabel('Pain location').fill('Left knee')
  await section.getByLabel('Pain severity (0–10)').fill('4')
  await section.getByRole('radio', { name: 'No', exact: true }).check()
  await section.getByRole('button', { name: 'Save feedback' }).click()
  await expect(section.locator('pre')).toContainText('"pain_reported": false')
  await expect(section.locator('pre')).toContainText('"pain_location": null')
  await expect(section.getByLabel('Pain location')).toHaveCount(0)
})

test('conversation failures retain drafts, retry sends once and clears only on success', async ({ page }) => {
  const section = page.locator('#conversation')
  await section.getByRole('switch', { name: 'Simulate message failure' }).check()
  await section.getByLabel('Message', { exact: true }).fill('Can I use a lighter load?')
  await section.getByRole('button', { name: 'Send message' }).click()
  await expect(section.getByRole('alert')).toContainText('Your message is still here.')
  await expect(section.getByLabel('Message', { exact: true })).toHaveValue('Can I use a lighter load?')
  await section.getByRole('switch', { name: 'Simulate message failure' }).uncheck()
  await section.getByRole('button', { name: 'Send message' }).click()
  await expect(section.getByRole('region', { name: 'Conversation messages' }).getByText('Can I use a lighter load?', { exact: true })).toHaveCount(1)
  await expect(section.getByLabel('Message', { exact: true })).toHaveValue('')
  await expect(section.getByRole('button', { name: 'Send message' })).toBeDisabled()
})

test('proposal apply and reject are explicit; stale proposals cannot apply', async ({ page }) => {
  const section = page.locator('#adaptation')
  await expect(section.getByLabel('Rest after complete round (s)').first()).toHaveValue('90')
  await expect(section.getByLabel('Rest after complete round (s)').last()).toHaveValue('120')
  await section.getByRole('button', { name: 'Apply to this workout' }).click()
  await expect(section.getByText('applied', { exact: true })).toBeVisible()
  await expect(section.getByRole('button', { name: 'Apply to this workout' })).toHaveCount(0)
  await section.getByRole('button', { name: 'Reset proposal' }).click()
  await section.getByRole('button', { name: 'Reject proposal', exact: true }).click()
  await expect(section.getByText('rejected', { exact: true })).toBeVisible()
  await section.getByRole('button', { name: 'Simulate programme change' }).click()
  await expect(section.getByText('Request a new proposal before applying changes.')).toBeVisible()
  await expect(section.getByRole('button', { name: 'Apply to this workout' })).toHaveCount(0)
})

test('request errors retain form entries; sync retry is an explicit state callback', async ({ page }) => {
  const accounts = page.locator('#accounts')
  await accounts.getByRole('switch', { name: 'Simulate request failure' }).check()
  await accounts.getByRole('textbox', { name: 'Client name' }).fill('Taylor')
  await accounts.getByRole('textbox', { name: 'Email' }).fill('taylor@example.test')
  await accounts.getByRole('button', { name: 'Invite client', exact: true }).click()
  await expect(accounts.getByText('Example server error. Your entries are still here.')).toBeVisible()
  await expect(accounts.getByRole('textbox', { name: 'Client name' })).toHaveValue('Taylor')
  await accounts.getByRole('switch', { name: 'Simulate request failure' }).uncheck()
  await accounts.getByRole('button', { name: 'Invite client', exact: true }).click()
  await expect(accounts.getByRole('status')).toHaveText('Request accepted in this demo.')
  const states = page.locator('#states')
  await states.getByRole('button', { name: 'Retry sync' }).click()
  await expect(states.getByText('Workout synced', { exact: true })).toBeVisible()
  await expect(states.getByRole('button', { name: 'Retry sync' })).toHaveCount(0)
})

test('the complete catalogue fits the viewport and exposes accessible controls', async ({ page }) => {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(accessibility.violations).toEqual([])
})
